apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-producer
  template:
    metadata:
      labels:
        app: news-producer
    spec:
      containers:
      - name: news-producer
        image: news-producer:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
