apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-model
  template:
    metadata:
      labels:
        app: trading-model
    spec:
      containers:
      - name: trading-model
        image: trading-model:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
